### ISSUE TITLE
Migration example (for MovableCoord User)

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-axes#107]
## Description

I'm using MovableCoord to implement horizontal scrolling.
https://codepen.io/egjs/pen/vgJyQP

I want to migrate to eg.axes.

please show me a horizontal scrolling example using eg.axes.

**Comment by changdongchun** [comment]
https://codepen.io/egjs/pen/WyZQdE
this example is very good.
It has been a great help to me.
by the way
One more question.
At the rotation event



$(window).on("rotate", function(e, info){
	/* x range chage source */
	axis.setTo({x: 0});//set x to 0
});

"MovableCoord" has "option" attribute.

**Comment by jongmoon** [comment]
@changdongchun Excuse me. I could not understand your question. Sorry for that. Your question is that `setTo` is not working on `rotate` event?

**Is `rotate` your custom event?** 
If then check if this event is fired or not.

**or Is`orientationchange` is your intend?**
Then it would be better to reference this document.

https://stackoverflow.com/a/9824480/6208362

**Comment by changdongchun** [comment]
"MovableCoord" have "option" attribute.
example...
$(window).on("rotate", function(e, info){
	//Width calculation source 
	**MovableCoordVars.option({max : [ Width_calculation  , 0 ]});**
	MovableCoordVars.setTo(0,0,0);
});

but 
axis has only "setTo" and no "option".

What is the internal function of "axis" to replace "option of  #MovableCoord"?

**Comment by jongmoon** [comment]
@changdongchun Sorry... I missed your last comment. 

You can change options by axis property of Axes instance.

In your case, It would be like follows.

```js
var axes = new eg.Axes({...});

$(window).on("rotate" => {
  // if you want to set range of x
  axes.axis.x.range = [min, max]; 

  // if you want to set range of y 
  axes.axis.y.range = [min, max]; 
});

```
For your information, I made a example of this.

https://codepen.io/egjs/pen/Owmzvb

![axes_options](https://user-images.githubusercontent.com/3255471/43127697-09b729fe-8f6b-11e8-8ea5-1fca40f88615.gif)


> As you mentioned, there is no documentation for this. it would make user very difficult to handle it. I'll consider it.
