### ISSUE TITLE
horizontal scrolling's bug in html fixed position 

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-axes#117]
## Description
<div style="position:fixed;left:0;right:0;top:0;height:50px">

horizontal scrolling

</div>

1. Normal operation is performed at the top of the scroll.
2. If you scroll down, the touch will not be intermittent.

**Occurs only on iOS.**

**Comment by jongmoon** [comment]
@changdongchun Thank you for reporting. We'll check soon!

**Comment by jongmoon** [comment]
@changdongchun Could you tell me the site or page that you had discovered this issue?

**Comment by changdongchun** [comment]
<!DOCTYPE html>
<html lang="ko">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=medium-dpi">
<meta name="theme-color" content="#ffffff">
<meta name="format-detection" content="telephone=no">
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://naver.github.io/egjs-axes/release/latest/dist/axes.pkgd.js"></script>


<style>
body { margin:0;padding:0; }
body,p,h1,h2,h3,h4,h5,h6,ul,ol,li,dl,dt,dd,table,th,td,form,fieldset,legend,input,textarea,button,select { margin:0;padding:0;-webkit-text-size-adjust:none; }
ul,ol { list-style:none; }
a { color:#333;text-decoration:none;cursor:pointer }
#testWrap {}
#testWrap .top { height:150px;background-color:#fff000; }
#testWrap .bot { position:relative;padding-top:80px;;background-color:#000fff; }
#testWrap .bot .tab { position:absolute;left:0;top:0;right:0;overflow:hidden;height:80px;background-color:#00fff0; }
#testWrap .bot .tab #scroller { position:absolute;-webkit-tap-highlight-color:rgba(0,0,0,0);-webkit-transform:translateZ(0);-moz-transform:translateZ(0);-ms-transform:translateZ(0);-o-transform:translateZ(0);transform:translateZ(0); }
#testWrap .bot .tab li { display:table-cell; }
#testWrap .bot .tab li a { display:block;padding:0 5px;line-height:80px;white-space:nowrap; }
#testWrap.fixed .bot .tab { position:fixed;left:0;top:0;right:0;height:80px;background-color:#00fff0; }
#testWrap .bot .cont { height:2500px; }
</style>
<script type="text/javascript">
	$(document).ready(function () {
		// 스크롤 Aaction
		$(window).scroll(function () {
			var yesGiftScrolls = $(window).scrollTop();

			if (yesGiftScrolls >= $(".bot").offset().top) {
				$("#testWrap").addClass("fixed");
			} else {
				$("#testWrap").removeClass("fixed");
			}
		});
	});
</script>
</head>
<body>


<div id="testWrap">
	<div class="top">
	</div>
	<div class="bot">
		<div class="tab">
			<div id="tabScl">
				<div id="scroller">
					<ul>
						<li><a href="#">가나다라</a></li>
						<li><a href="#">오육칠팔</a></li>
						<li><a href="#">사요나라</a></li>
						<li><a href="#">기승전결</a></li>
						<li><a href="#">우리나라</a></li>
						<li><a href="#">대한민국</a></li>
					</ul>
				</div>
			</div>
			<script type="text/javascript">
				var wSellerGScroller = 0;
				if( $("#tabScl #scroller").width() < $("#tabScl").width() )
				{
					wSellerGScroller = 0;
				} else {
					wSellerGScroller = $("#tabScl #scroller").width() - $("#tabScl").width();
				}
				var options = { deceleration:0.0024 };
				var sellerGScroller_input = new eg.Axes.PanInput($("#tabScl"), {
					scale: [1, 0]
				});
				var $scroller_seller = $("#tabScl #scroller");
				var sellerGScroller = new eg.Axes({
					x: {
						range: [-wSellerGScroller, 0],
						bounce : [100, 100]
					}
				}, options).on({
					"change" : function(evt) {
						//document.getElementById("scroller").style.transform = "translateX(" + evt.pos.x + "px)";
						//$scroller_seller.css('transform', "translateX(" + evt.pos.x + "px)")
						//scroller.style.transform = "translateX(" + evt.pos.x + "px)";
						$scroller_seller[0].style.transform = "translateX(" + evt.pos.x + "px)";
					}
				});
				
				sellerGScroller.setTo({x: 0});//set x to 0
				sellerGScroller.connect(["x"], sellerGScroller_input);

				$(window).on("rotate", function(e, info){
					var wSellerGScroller = 0;
					if( $("#tabScl #scroller").width() < $("#tabScl").width() )
					{
						wSellerGScroller = 0;
					} else {
						wSellerGScroller = $("#tabScl #scroller").width() - $("#tabScl").width();
					}
					sellerGScroller.axis.x.range = [-wSellerGScroller, 0]; 
					sellerGScroller.setTo({x: 0});//set x to 0
				});

				$(window).on("resize", function(e, info){
					var wSellerGScroller = 0;
					if( $("#tabScl #scroller").width() < $("#tabScl").width() )
					{
						wSellerGScroller = 0;
					} else {
						wSellerGScroller = $("#tabScl #scroller").width() - $("#tabScl").width();
					}
					sellerGScroller.axis.x.range = [-wSellerGScroller, 0]; 
					sellerGScroller.setTo({x: 0});//set x to 0
				});
			</script>
		</div>
		<div class="cont">
		</div>
	</div>
</div>


</body>
</html>

**Comment by jongmoon** [comment]
@changdongchun Sorry, I can not reproduce your case. If you mean scroll down is not working intermittently when touching on axes area?

(죄송하지만 제가 정확하게 재현할 수 없었습니다. ㅜㅜ 수평 스크롤이 잘 안된다는 의미이신 것 같은데요? 조금 더 구체적인 재현 방법을 좀 알려주실 수 있으실런지요? 1. 스크롤 상단에서는 정상적으로 수평스크롤 되지만, 2. 페이지 아래로 스크롤을 한 후에 터치를 하면 터치가 가끔씩 동작하지 않는다고 리포팅 주신 것 같습니다. 혹시 제가 이해한 것과 다르다면 좀더 자세한 말씀 적어주십사 부탁드리고 싶습니다.)

![reproducing-axes](https://user-images.githubusercontent.com/3255471/50134755-e59b6700-02d4-11e9-83f8-d0af3a7753e3.gif)

**Comment by changdongchun** [comment]
가로 스크롤 하는 영역(axes)가 쌓인 div에 fixed 속성이 들어갈 경우 스크롤 후 터치하면 가로스크롤 동작이 간헐적으로 안되고 있습니다.

**Comment by jongmoon** [comment]
@changdongchun 실례지만 iOS 버전과 어떤 브라우저를 사용하시는지 알 수 있을까요?
Can I ask you the iOS version and browser spec?

**Comment by jongmoon** [comment]
@changdongchun I can reproduce it!

**Comment by jongmoon** [comment]
@changdongchun If you have any idea or opinion, feel free to write issues. Thank you once again for reporting issues!

**Comment by changdongchun** [comment]
모바일다음웰컴 페이지의 경우 fixed인 가로스크롤에서 ios에서 정상동작을 하고 있는데 별도의 hack을 쓴것일까요? https://m.daum.net/

**Comment by jongmoon** [comment]
@changdongchun 확인 후 피드백 드리도록 하겠습니다~  (I'll check it!)

**Comment by jongmoon** [comment]
@changdongchun 
After a few checks, I've found that the touch event does not occur when you dynamically specify the `fixed` attribute. In the case of the codepen example given, if you force the `fixed` attribute to be statically forced, the touch event will normally occur. (in iOS Safari)

 In the case of https://m.daum.net/, the site consists of two scrollers. The scroller specified with fixed is always given the fixed attribute, and it appears that @changdongchun has implemented its intention through the visibility property.

> 몇 가지 확인한 결과 동적으로 `fixed` 속성을 지정하는 경우에 touch 이벤트가 발생하지 않는 것으로 확인했습니다. 전달 주신 codepen 예제의 경우 `fixed` 속성을 정적으로 강제로 지정해 두면 정상적으로 touch 이벤트가 발생합니다. (in iOS Safari)
> 
> https://m.daum.net/ 의 경우 본 이슈를 알고 있었는지 2개의 scroller 를 구성하였네요. fixed 로 지정한 scroller 는 항상 fixed 속성이 부여되어 있고 visibility 속성을 통해 @changdongchun 님이 의도하신 바를 구현한 것으로 보입니다.

**Comment by changdongchun** [comment]
안녕하세요 이번에 네이버 모바일 메인에서 상단 고정의 가로스크롤은 daum과는 다르게 하나의 scroller인것 같은데요 이번에 egJs에서도 관련된 업데이트가 가능할까요?

**Comment by jongmoon** [comment]
@changdongchun NAVER does not apply `position:fixed` dynamically.

> 이 이슈의 핵심은 스크롤하고자 하는 영역에 동적으로 fixed 속성을 부여하는 경우에 발생하는 것 입니다. (보내주신 코드펜 예제가 딱 그런 예제이지요). 
>
> 저희(네이버)의 경우 scroller 를 하나만 사용하지만 fixed 속성을 동적으로 부여하지 않습니다. 보여지고 안보여지는 처리는 transform 속성을 이용하여 Layer 자체를 이동하는 방식을 적용합니다. 이로 인해 fixed 를 적용했지만 안보여질 수 있게 됩니다.
>
> 아쉽게도 이 이슈는 브라우저에서 해결해주지 않으면 이벤트를 핸들링 할 수 없는 상황입니다.

**Comment by changdongchun** [comment]
많은 도움이 되었습니다. 감사합니다~

**Comment by changdongchun** [comment]
> @changdongchun NAVER does not apply `position:fixed` dynamically.
> 
> > 이 이슈의 핵심은 스크롤하고자 하는 영역에 동적으로 fixed 속성을 부여하는 경우에 발생하는 것 입니다. (보내주신 코드펜 예제가 딱 그런 예제이지요).
> > 저희(네이버)의 경우 scroller 를 하나만 사용하지만 fixed 속성을 동적으로 부여하지 않습니다. 보여지고 안보여지는 처리는 transform 속성을 이용하여 Layer 자체를 이동하는 방식을 적용합니다. 이로 인해 fixed 를 적용했지만 안보여질 수 있게 됩니다.
> > 아쉽게도 이 이슈는 브라우저에서 해결해주지 않으면 이벤트를 핸들링 할 수 없는 상황입니다.

많은 도움이 되었습니다. 감사합니다.

**Comment by changdongchun** [comment]
최근 네이버 언론사 페이지에서는 상단 다음과 같은 방식이 아니라 하나의 영역이 fixed와 static을 동시에 보여주고 있는데요 https://media.naver.com/press/214 네이버 언론사 페이지 가로 스크롤은 egjs-axes 을 활용한 것이 아닌가요?

**Comment by changdongchun** [comment]
> @changdongchun NAVER does not apply `position:fixed` dynamically.
> 
> > 이 이슈의 핵심은 스크롤하고자 하는 영역에 동적으로 fixed 속성을 부여하는 경우에 발생하는 것 입니다. (보내주신 코드펜 예제가 딱 그런 예제이지요).
> > 저희(네이버)의 경우 scroller 를 하나만 사용하지만 fixed 속성을 동적으로 부여하지 않습니다. 보여지고 안보여지는 처리는 transform 속성을 이용하여 Layer 자체를 이동하는 방식을 적용합니다. 이로 인해 fixed 를 적용했지만 안보여질 수 있게 됩니다.
> > 아쉽게도 이 이슈는 브라우저에서 해결해주지 않으면 이벤트를 핸들링 할 수 없는 상황입니다.



최근 네이버 언론사 페이지에서는 상단 다음과 같은 방식이 아니라 하나의 영역이 fixed와 static을 동시에 보여주고 있는데요 https://media.naver.com/press/214 네이버 언론사 페이지 가로 스크롤은 egjs-axes 을 활용한 것이 아닌가요?
