### ISSUE TITLE
horizontal scrolling's bug in html fixed position - 2

### ISSUE THREAD

**Issue by changdongchun** [naver/egjs-axes#135]
## Description

https://media.naver.com/press/055
와 같이 상단 고정인데 가로 스크롤인 케이스를
egjs-axes를 활용한 예제로 제공이 안될까요?

**Comment by jongmoon** [comment]
As I mentioned in @changdongchun # 117, the first example given by @changdongchun in codepen showed that if the fixed attribute is dynamically assigned to the area, the touch event itself does not occur in the iOS Safari browser at all. So, using a component other than axes does not solve the problem.

However, even though it is a similar case, the news (media) page shows a normal operation.

At this time, we are keeping in mind the possibility that touch events could occur through HTML structured resolution. We'll be happy to review this part and give you feedback.

ps. Even if you can not give feedback quickly due to schedule issue, please ask for your understanding in advance.

> @changdongchun #117 에서 언급드렸던 것처럼, 처음 @changdongchun 님께서 codepen 을 통해 알려주신 예제 에서는 해당 영역에 fixed 속성을 동적으로 부여한 경우 iOS 의 사파리 브라우저에서는 아예 touch 이벤트 자체가 발생하지 않는 상황이었습니다. 그래서 axes 가 아닌 다른 컴포넌트를 사용하더라도 문제를 해결할 수 없는 문제인데요. 
>
> 그러나 유사 케이스임에도 불구하고 뉴스(미디어) 페이지의 경우는 정상적으로 동작하는 모습을 보여주고 있습니다. 
>
> 현재로서는 HTML 구조적인 해결을 통해 터치 이벤트가 발생할 수 있게 된 가능성을 염두 해 두고 있습니다. 이 부분은 저희도 추가 검토하고 피드백 드릴 수 있도록 하겠습니다.
>
> ps. 일정 이슈로 빠르게 피드백 드리지 못하더라도 미리 너그러이 양해해 주시길 부탁드립니다..

**Comment by changdongchun** [comment]
> As I mentioned in @changdongchun # 117, the first example given by @changdongchun in codepen showed that if the fixed attribute is dynamically assigned to the area, the touch event sometimes does not occur in the iOS Safari browser at all. So, using a component other than axes does not solve the problem.
> 
> However, even though it is a similar case, the news (media) page shows a normal operation.
> 
> At this time, we are keeping in mind the possibility that touch events could occur through HTML structured resolution. We'll be happy to review this part and give you feedback.
> 
> ps. Even if you can not give feedback quickly due to schedule issue, please ask for your understanding in advance.
> 
> > @changdongchun #117 에서 언급드렸던 것처럼, 처음 @changdongchun 님께서 codepen 을 통해 알려주신 예제 에서는 해당 영역에 fixed 속성을 동적으로 부여한 경우 iOS 의 사파리 브라우저에서는 touch 이벤트가 간헐적으로 발생하지 않는 상황이었습니다. 그래서 axes 가 아닌 다른 컴포넌트를 사용하더라도 근본적으로 문제를 해결할 수 없는 문제인데요.
> > 그러나 유사 케이스임에도 불구하고 뉴스(미디어) 페이지의 경우는 정상적으로 동작하는 모습을 보여주고 있습니다.
> > 현재로서는 HTML 구조적인 해결을 통해 터치 이벤트가 발생할 수 있게 된 가능성을 염두 해 두고 있습니다. 이 부분은 저희도 추가 검토하고 피드백 드릴 수 있도록 하겠습니다.
> > ps. 일정 이슈로 빠르게 피드백 드리지 못하더라도 미리 너그러이 양해해 주시길 부탁드립니다..

2012년  jindo부터 꾸준히 네이버의 API를 써왔는데요. 너무나 감사합니다. 좋은 하루 보내세요.

**Comment by changdongchun** [comment]
IOS 13베타 사파리에서 확인 시 가로 스크롤 액션 후 세로로 튕겨 올라가지는 현상들이 발생하는데요. 혹시 내부 소스 중 강제로 새로로 움직이는 소스등이 가로스크롤 액션과 충돌이 날 수도있나요?

**Comment by daybrush** [comment]
@changdongchun 

안녕하세요. 확인해봤는데 iOS 13부터 PointerEvent와 touch-action: pan-y를 지원합니다.

하지만 원래 동작으로 봤을 땐
* 가로로 터치 이동 => 세로로 터치 이동하면 스크롤이 발생하지 않습니다.
하지만 iOS13에서는
* 세로로 터치 이동하는 순간 무조건 스크롤이 발생합니다. 

스크롤이 발생할 때 pointercancel 이벤트가 발생하면서 axes의 동작이 끝나버립니다.
iOS13 정식 버전에서는 어떻게 될지 모르지만 일단 아래와 같이 inputType을 pointer를 빼면 가능해집니다.

```
var sellerGScroller_input = new eg.Axes.PanInput($("#tabScl"), {
    inputType: ["touch", "mouse"],
    scale: [1, 0],
});
```


---

Hello, I checked.  iOS 13 support PointerEvent and touch-action: pan-y.

based on the way it works,
* Touch movement horizontally => Touch movement vertically does not occur scrolling.
But in iOS 13,
* Any time you touch it vertically, it will scroll through. 

When scrolling occurs, a pointercancel event occurs, Axes ended.

I don't know what will happen with iOS13's official version, but it's possible to remove PointerEvent from `inputType` as shown below.



```
var sellerGScroller_input = new eg.Axes.PanInput($("#tabScl"), {
    inputType: ["touch", "mouse"],
    scale: [1, 0],
});
```

**Comment by changdongchun** [comment]
정상으로 동작함을 확인하였습니다. 감사합니다.
p.s. 혹시 position fixed 일때 동작은 아직 대기해야 하는 것이겠죠?

**Comment by daybrush** [comment]
@changdongchun
 
정확한 이유는  모르겠는데 document에 아무 의미 없는 touchmove 이벤트 추가해보실래요?

```js
document.addEventListener("touchmove", (e) => {
    // console.log("document, touchmove", e.target);
});
```
