### ISSUE TITLE
Supports extend plugins

### ISSUE THREAD

**Issue by sculove** [naver/egjs-axes#14]
## Description
MovableCoord is a raw(?) component.
Threrefore, movablecoord is so extensible.  but, movablecoord is so hard to use it.

the Extend plugin is so simple class.
if you want to use scroll UI, you can use like this.
```js
new eg.MovableCoord.Scroll('#wrapper', {
    scrollX : true,
    scrollY : false,
    mouseWheel: true,
    scrollbars: true
});
```

### Goals: supports so simple component.

**Comment by jongmoon** [comment]
This issue is no more valid.
