### ISSUE TITLE
MovableCoord - increase default threashold value options for Hammer

### ISSUE THREAD

**Issue by sculove** [naver/egjs-axes#39]
@jongmoon commented on [Wed Jul 13 2016](https://github.com/naver/egjs/issues/291)

## Description

It's not a bug. but It is need to be discussed.

current threashold = 0,
But in recent device browsers, browser sends `touch offset` more correctly(?) . So when moved vertically or horizontally, sometimes Hammer does not recognize it as vertical  or horizontal perfectly.

For example when you touches screen vertically on HORIZONTAL mode, Hammer sometimes thinks it as horizontal movement by 1~ 2px.

---

@sculove commented on [Thu Jul 14 2016](https://github.com/naver/egjs/issues/291#issuecomment-232535935)

@jongmoon Could you give us some information like browser test?

**Comment by arkist** [comment]
fyi, Hammer's default pan threshold is [10](https://github.com/hammerjs/hammer.js/blob/master/src/recognizers/pan.js#L87).
but I don't know why. 🤔
