### ISSUE TITLE
Coordinate.ts - getInsidePosition

### ISSUE THREAD

**Issue by hikaMaeng** [naver/egjs-axes#41]
According to the unit test(https://goo.gl/G2kNn6), range param is given as [start, end] and 
always start <end.  therefore No need to iterate the algorithm in the return statement.

current code
```javascript
  toDestPos = Math.max(targetRange[0], toDestPos);
  toDestPos = Math.min(targetRange[1], toDestPos);
return +Math.min(targetRange[1], Math.max(targetRange[0], toDestPos)).toFixed(5);
```
recommand
```javascript
  toDestPos = Math.max(targetRange[0], toDestPos);
  toDestPos = Math.min(targetRange[1], toDestPos);
return +toDestPos.toFixed(5);
```

**Comment by sculove** [comment]
Thanks. Could you give me a pr please?

**Comment by hikaMaeng** [comment]
I'll try..
I didn't yet set local environment for egjs ^^;
