### ISSUE TITLE
PinchInputType need to return offset value which calculated with base value

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-axes#45]
# Problem
The zoomming UI using pinch gesture can not be implemented correctly using the offset value returned by PinchInputType at present.

# Problem Description
The PinchInputType returns the offset value of the difference in scale value provided by the hammer's pinch recognizer.

If the offset given by PinchInputType is cumulatively added, the size and scale of the change will be the same. This scale value is relative value to the value at the pinchstart point.

The coordinate value handled by axes is an absolute value. The problem is to add the relative offset value to the absolute coordinate value.

# How to resolve
To solve this problem, the offset value should return the difference of the absolute coordinate value to be changed due to the scale value.

To do this, you can add an item called `base` to the `option` property and allocate the absolute coordinate value at the point of pinchstart so that it can be used for offset calculation.

**Comment by sculove** [comment]
If Axes.PinchInput can know axis information when holding, PinchInput handle it.
I will provide `observer.get` method. 
this method returns axis information connected InputType.

**Comment by sculove** [comment]
I updated wiki pages
- https://github.com/naver/egjs-axes/wiki/How-to-create-a-custom-InputType
- https://github.com/naver/egjs-axes/wiki/%EC%9E%90%EC%8B%A0%EB%A7%8C%EC%9D%98-eg.Axes-InputType%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%A7%8C%EB%93%9C%EB%8A%94%EA%B0%80%3F
