### ISSUE TITLE
new event suggestion

### ISSUE THREAD

**Issue by vreality64** [naver/egjs-axes#69]
## Description
A triggered event is required after all actions have been completed.

Take the snap function of iScroll as an example. Currently, I have to check both `animationEnd` event handler and `release` event handler.

```js
// animationEnd
const onAnimationEnd = (event) => {
    snap()
}

// release
const onRelease = (event) => {
    if (event.depaPos === event.pestPos) {
        // animationEnd is not fired. so snap function performed here.
        snap()
    } else {
        // animation will be performed. so animationEnd event will be triggered.
    }
}
```

I think some event will be helpful in this situation.

```js
const onFinish = (event) => {
    snap()
}
```

**Comment by sculove** [comment]
@vreality64 Good idea. we are consider it. thanks
