### ISSUE TITLE
information inconsistency on release event

### ISSUE THREAD

**Issue by vreality64** [naver/egjs-axes#70]
## Description
I think `animationEnd` event will be fired when `depsPos` is not equal `destPos` on release time.
It is reasonable because if there are some change in position, it have to be moved with animation.

but **when I slightly move position, animationEnd event wasn't fired**.

I found the reason is [duration](https://github.com/naver/egjs-axes/blob/a7df075c67ecf52945a2b5ed89f455c4713e3f53/src/Coordinate.ts#L28).
> when duration is under 100, then value is zero

It's okay if animation was not performed, but It's not okay that information was hided.

## Steps to check or reproduce

here are [codepen link](https://codepen.io/ian-park/pen/VMXBXp?editors=1111)
- check console
- second information (Object) is delta
- move slightly until delta is not zero
- animationEnd will not be fired

**Comment by sculove** [comment]
@vreality64 you're right it's a bug.
next release we will fix it. Thanks
