### ISSUE TITLE
There are teleportation in restore

### ISSUE THREAD

**Issue by vreality64** [naver/egjs-axes#72]
## Description

![restore animation](https://user-images.githubusercontent.com/886706/31850516-2c73992a-b68e-11e7-9197-b0044419903b.gif)
You can see teleportation when user release touch.

This occurs when `deceleration` value is high
And high deceleration leads `Coordinate.getDuration` make **duration zero**.

## Steps to check or reproduce

Here are [codepen link](https://codepen.io/ian-park/pen/RLObpX). I changed only **deceleration** value to **0.01** on axes demo.
- check link on mobile size
- move a little bit

**Comment by sculove** [comment]
thanks your reports
