### ISSUE TITLE
Should cancel animation when "hold" event is triggered.

### ISSUE THREAD

**Issue by happyhj** [naver/egjs-axes#74]
I think axes should **cancel animation** when "hold" event is triggered.

For example, in the case of Pan input type, 
if the touch is started again during the animation, 
the reaction starts after **all the animation ends**.
So, the reactivity is not good.

After touch start, I think the animation should be stopped and the reaction should begin immediately.

Is there any method to stop animation when "hold" event is triggered?

**Comment by jongmoon** [comment]
It's fixed by https://github.com/naver/egjs-axes/pull/73#pullrequestreview-72449198
  - Animation grab not working
