### ISSUE TITLE
Need to prevent the latent error

### ISSUE THREAD

**Issue by netil** [naver/egjs-axes#84]
## Description

The below code block, it's trying to destroy `hammer` instance, but when seeing the condition, it's within `else` clause which means there's possibility being null value of `this.hammer`.

https://github.com/naver/egjs-axes/blob/b1ec26112d5c6c08452e80b0f7a07cba80643171/src/inputType/PinchInput.ts#L87-L94

It should be preventing by checking the instance as `this.hammer && this.hammer.destroy();`

**Comment by sculove** [comment]
@netil thanks
